# Generated by Django 4.2.17 on 2025-03-20 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_poster_path_watchlist_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
